# Generated by Django 3.2.22 on 2024-02-07 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inputquerymodel',
            name='material_factor',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='inputquerymodel',
            name='price_factor',
            field=models.FloatField(default=1),
        ),
        migrations.AddField(
            model_name='inputquerymodel',
            name='surface_factor',
            field=models.FloatField(default=1),
        ),
    ]
