# Generated by Django 3.2.22 on 2024-02-14 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20240207_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstimateCleaningPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cleaning_price', models.FloatField(blank=True, null=True)),
                ('currency_sign', models.CharField(max_length=10)),
                ('cleaning_frequency', models.FloatField(default=1)),
                ('product_condition', models.FloatField(default=1)),
                ('user_cleaning_price', models.FloatField(blank=True, null=True)),
                ('response_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_cleaning_price', to='home.responsedatamodel')),
            ],
        ),
    ]
