# Generated by Django 3.2.22 on 2024-02-14 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_estimatecleaningprice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estimatecleaningprice',
            old_name='Cleaning_price',
            new_name='cleaning_price',
        ),
    ]
