# Generated by Django 3.2.22 on 2024-02-14 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_cleaning_price_estimatecleaningprice_cleaning_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimatecleaningprice',
            name='cleaning_frequency',
            field=models.CharField(default='one_time', max_length=20),
        ),
        migrations.AlterField(
            model_name='estimatecleaningprice',
            name='product_condition',
            field=models.CharField(default='Good', max_length=20),
        ),
    ]
